### ISSUE TITLE
README補足

### ISSUE THREAD

**Issue by nao-kasai** [fourdigit/gulpset#13]
手順通り進めても上手くいかないので、補足情報を書いときます。

・5. npm install 
第2項は、auto-install を実行（yarn auto-install ではない）

・run-sequenceが必要なので、yarn add run-sequence 実行。

・run-sequenceを入れると、gulp dev実行時に、gulp.hasTask is not a function のエラーが出る。
→ gulpのバージョンを、3.9.1に落とす必要あり。

・package.jsonの設定値を、"gulp": "^4.0.0” から、"gulp": "^3.9.1"に書き換える。

・package-lock.jsonとyarn.lockの２ファイルを削除。

・yarn を実行し、node_modulesを再インストール。これで正常に動きました！

**Comment by TakuyaAbe** [comment]
#16 で解決しているはずですのでcloseします。
