### ISSUE TITLE
デプロイ機能

### ISSUE THREAD

**Issue by marihemo** [fourdigit/gulpset#6]
あったら嬉しい

**Comment by TakuyaAbe** [comment]
@marihemo @ri-ie 
https://github.com/fourdigit/gulpset/releases/tag/v3.0.1
にて、deploysyncというタスクを追加しました。
readmeにありますが、下記のように設定するとrsyncを使ってファイルがデプロイされます。

1. Open `/gulpset/tasks/deployrsync/index.js`
2. Set target user:hostname to `gulpset.confs.deployrsync.options.hostname`
3. Add private key of target server. e.g. `ssh-add ~/.ssh/xxxxxxxx_rsa`
4. Run `gulp deployrsync`

つかってみて何か不具合があったらissueをreopenしてください。
